# Generated by Django 5.0.6 on 2024-05-15 15:51

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_order_original_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
