# Generated by Django 5.0.6 on 2024-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
