# Generated by Django 3.2.25 on 2024-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20240501_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
