# Generated by Django 3.2.25 on 2024-05-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
    ]
